# TODO: localize
displayName: "Hakka Dictionary"
# TODO: determine best default language
defaultSubApp: raoping_subapp
subApps:
  sixian_subapp:
    displayName: "四縣 (Sixian)"
  hailu_subapp:
    displayName: "海陸 (Hailu)"
  dapu_subapp:
    displayName: "大埔 (Dapu)"
  raoping_subapp:
    displayName: "饒平 (Raoping)"
  zhaoan_subapp:
    displayName: "詔安 (Zhaoan)"
  southern_sixian_subapp:
    displayName: "南四 (SouthernSixian)"
