dbList:
  - TWMOEHakkaDict

enabledDBs:
  sixian_subapp:
    - TWMOEHakkaDict: sixian_view
  hailu_subapp:
    - TWMOEHakkaDict: hailu_view
  dapu_subapp:
    - TWMOEHakkaDict: dapu_view
  raoping_subapp:
    - TWMOEHakkaDict: raoping_view
  zhaoan_subapp:
    - TWMOEHakkaDict: zhaoan_view
  southern_sixian_subapp:
    - TWMOEHakkaDict: southern_sixian_view


# TODO: put in dialect config

dbConfigs:
  TWMOEHakkaDict:
    displayNames:
      eng_us: "Taiwan Ministry of Education Hakka Dictionary"

    views:
      southern_sixian_view:
        displayableFields:
          filtrex: 'dialect in ("mand_tw", "tw_hakka_southern_sixian", "tw_hakka_southern_sixian_pronunciation")'
        searchableFields:
          filtrex: 'dialect in ("mand_tw", "tw_hakka_southern_sixian", "tw_hakka_southern_sixian_pronunciation")'
      sixian_view:
        displayableFields:
          filtrex: 'dialect in ("mand_tw", "tw_hakka_sixian", "tw_hakka_sixian_pronunciation")'
        searchableFields:
          filtrex: 'dialect in ("mand_tw", "tw_hakka_sixian", "tw_hakka_sixian_pronunciation")'
      hailu_view:
        displayableFields:
          filtrex: 'dialect in ("mand_tw", "tw_hakka_hailu", "tw_hakka_hailu_pronunciation")'
        searchableFields:
          filtrex: 'dialect in ("mand_tw", "tw_hakka_hailu", "tw_hakka_hailu_pronunciation")'
      dapu_view:
        displayableFields:
          filtrex: 'dialect in ("mand_tw", "tw_hakka_dapu", "tw_hakka_dapu_pronunciation")'
        searchableFields:
          filtrex: 'dialect in ("mand_tw", "tw_hakka_dapu", "tw_hakka_dapu_pronunciation")'
      raoping_view:
        displayableFields:
          filtrex: 'dialect in ("mand_tw", "tw_hakka_raoping", "tw_hakka_raoping_pronunciation")'
        searchableFields:
          filtrex: 'dialect in ("mand_tw", "tw_hakka_raoping", "tw_hakka_raoping_pronunciation")'
      zhaoan_view:
        displayableFields:
          filtrex: 'dialect in ("mand_tw", "tw_hakka_zhaoan", "tw_hakka_zhaoan_pronunciation")'
        searchableFields:
          filtrex: 'dialect in ("mand_tw", "tw_hakka_zhaoan", "tw_hakka_zhaoan_pronunciation")'

    source: "https://hakkadict.moe.edu.tw/"
    license: "CC BY-ND 3.0 TW"

    loadInfo:
      localCSV: /db/languages/Hakka/HakkaMOE.csv

#    viewInfo = {
#      allowedTags: {
#        [tagType]: verifiedTagID[]
#      }
#      searchableFields: fieldID[]
#    }


    primaryKey: MOESystemEntryID

    fields:
      MOESystemEntryID:
        type:
          dictionary: id

      Headword:
        type:
          dictionary: vocab
        # TODO: is this correct?
        dialect: mand_tw

      PartOfSpeech:
        type:
          dictionary: pos_classification

      LexicalIndexClassification:
        type:
          # TODO: is this correct?
          dictionary: pos_classification

      SixianHakkaPronunciation:
        type:
          dictionary: pronunciation
        dialect: tw_hakka_sixian_pronunciation

      HailuHakkaPronunciation:
        type:
          dictionary: pronunciation
        dialect: tw_hakka_hailu_pronunciation

      DapuHakkaPronunciation:
        type:
          dictionary: pronunciation
        dialect: tw_hakka_dapu_pronunciation

      RaopingHakkaPronunciation:
        type:
          dictionary: pronunciation
        dialect: tw_hakka_raoping_pronunciation

      ZhaoanHakkaPronunciation:
        type:
          dictionary: pronunciation
        dialect: tw_hakka_zhaoan_pronunciation

      SouthernSixianHakkaPronounciation:
        type:
          dictionary: pronunciation
        dialect: tw_hakka_southern_sixian_pronunciation

      Definition:
        type:
          dictionary: definition
        dialect: mand_tw
        delimiterRegex: (?<=。)\s*(?=[0-9])

      # Dialect?
      Synonyms:
        type:
          dictionary: synonym

      Antonyms:
        type:
          dictionary: opposite

      CorrespondingMandarin:
        type:
          dictionary: definition

      DapuHakkaRelatedWords:
        type:
          dictionary: related_words
        dialect: tw_hakka_dapu

      DapuHakkaRelatedWordsPronunciation:
        type:
          dictionary: related_words_pronunciation
        dialect: tw_hakka_dapu_pronunciation

      RaopingHakkaRelatedWords:
        type:
          dictionary: related_words
        dialect: tw_hakka_raoping

      RaopingHakkaRelatedWordsPronunciation:
        type:
          dictionary: related_words_pronunciation
        dialect: tw_hakka_raoping_pronunciation

      ZhaoanHakkaRelatedWords:
        type:
          dictionary: related_words
        dialect: tw_hakka_zhaoan

      ZhaoanHakkaRelatedWordsPronunciation:
        type:
          dictionary: related_words_pronunciation
        dialect: tw_hakka_zhaoan_pronunciation

      SouthernSixianHakkaRelatedWords:
        type:
          dictionary: related_words
        dialect: tw_hakka_southern_sixian

      SouthernSixianHakkaRelatedWordsPronunciation:
        type:
          dictionary: related_words_pronunciation
        dialect: tw_hakka_southern_sixian_pronunciation
