displayName: "Chhâ Tâi-gí!"
apps:
  - taigi.us

indexHtml:
  manifest: "/manifests/chhataigi/site.webmanifest"
  favicon: "/icons/chhataigi/favicon.ico"
  themeColor: "#000000"
  og:
    imageFullURL: "https://taigi.us/icons/chhataigi/tw-flag-full.png"
    description: "A local search engine for researching words and phrases in Tâi-gí."

  noscript: "For Taiwanese, you can also try out  <a href=\"https://chhoe.taigi.info/\">ChhoeTaigi</a>, which was an inspiration for this site."
