displayName: "Chhâ Tâi-gí!"
defaultSubApp: "eng_poj"
#domainToubefaultSubAppMapping:
#  taigi.us: "eng_poj"
#  kip.taigi.us: "eng_kip"
#  mandopoj.taigi.us: "mando_poj"
#  mandokip.taigi.us: "mando_kip"

# NOTE: displayNames per language can be implemented without too much trouble, if needed
subApps:
  eng_poj:
    displayName: "English ↔ Pe̍h-ōe-jī"
    blacklistDialectsRegex: kip
  eng_kip:
    displayName: "English ↔ Kàu-io̍k-pōo"
    blacklistDialectsRegex: poj
  mando_poj:
    displayName: "漢字 ↔ Pe̍h-ōe-jī"
    blacklistDialectsRegex: kip
  mando_kip:
    displayName: "漢字 ↔ Kàu-io̍k-pōo"
    blacklistDialectsRegex: poj
  all_poj:
    displayName: "All DBs / 所有數據庫 (Pe̍h-ōe-jī)"
    blacklistDialectsRegex: kip
  all_kip:
    displayName: "All DBs / 所有數據庫 (Kàu-io̍k-pōo)"
    blacklistDialectsRegex: poj

# NOTE: font sets per subapp can be implemented, but it's likely that per-app is more than sufficient for most use cases
# NOTE: font families listed here are applied globally, in the order they are first seen.
fonts:
  -
    type: "custom"
    family: "Noto Sans TC"
    localUrl: "/fonts/NotoSansTC-Regular.woff2"
  -
    type: "custom"
    family: "Noto Sans TC"
    localUrl: "/fonts/NotoSansTC-Bold.woff2"
    descriptors:
      weight: "700"
  -
    type: "system"
    family: "sans-serif"
