displayName: "Afrikaans - English FreeDict Test"
defaultSubApp: both
subApps:
  engToAfr:
    displayName: "English To Afrikaans"
  afrToEng:
    displayName: "Afrikaans na Engels"
  both:
    displayName: "Both Ways / Beide Kante"
