dbList:
  - eng_afr
  - afr_eng

enabledDBs:
  engToAfr:
    - eng_afr
  afrToEng:
    - afr_eng
  both:
    - eng_afr
    - afr_eng

dbConfigs:
  eng_afr:
    displayNames:
      eng_us: English → Afrikaans

    loadInfo:
      localCSV: /db/languages/FreeDictTestEngAfr/eng_afr.csv

    primaryKey: Id

    license: "GPL 2.0"
    source: "https://github.com/freedict/fd-dictionaries/tree/master/eng-afr"

    searchableFields:
      - English
      - Afrikaans

    fields:
      Id:
        type:
          dictionary: id

      English:
        type:
          dictionary: vocab

      EnglishIPA:
        type:
          dictionary: vocab_other

      Afrikaans:
        type:
          dictionary: definition
        delimiter: ❄

  afr_eng:
    displayNames:
      eng_us: Afrikaans → English

    loadInfo:
      localCSV: /db/languages/FreeDictTestEngAfr/afr_eng.csv

    primaryKey: Id

    license: "GPL 2.0"
    source: "https://github.com/freedict/fd-dictionaries/tree/master/afr-eng"

    searchableFields:
      - Afrikaans
      - English

    fields:
      Id:
        type:
          dictionary: id

      Afrikaans:
        type:
          dictionary: vocab

      AfrikaansIPA:
        type:
          dictionary: vocab_other

      English:
        type:
          dictionary: definition
        delimiter: ❄
